services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users_api
      #this ENV variable is only required for the healthcheck section - if you don't specify it, the check command will fail stating the root user doesn't exist in posgres
      PGUSER: "root"
    ports:
      - "8001:5432"
    networks:
      - network     
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d users_api" ]
      interval: 5s
      timeout: 5s
      retries: 5
  liquibase:
    build: ./db/liquibase/
    depends_on:
      postgres:
        condition: service_healthy
    command: liquibase --url=jdbc:postgresql://postgres:5432/users_api --username=root --password=root update
    networks:
      - network  
  # postgrestesting:
  #   build: .
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: testDB
  #   ports:
  #     - "8003:5432"
  #   restart: unless-stopped
  #   networks:
  #     - network
  # rabbitmq:
  #   image: rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: root
  #     RABBITMQ_DEFAULT_PASS: root
  #   ports:
  #     - "8002:5672"
  #   networks:
  #     - network  
networks:
  network:
    driver: bridge
    name: currency_rates_network 
